add!: cli

diff --git a/euler b/euler
--- a/euler
+++ b/euler
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
 set -e
 
-# Defaults
 PROB=""
 LANG=""
 
-# Parse args like p=10 lang=c
+
 for arg in "$@"; do
-  case $arg in
+  case "$arg" in
     p=*)
       PROB="${arg#p=}"
       ;;
@@ -27,18 +26,24 @@ if [[ -z "$PROB" || -z "$LANG" ]]; then
 fi
 
 DIR="p${PROB}"
-mkdir -p "$DIR"
 
-# -----------------------
-# Fetch problem statement
-# -----------------------
+if [[ -e "$DIR" ]]; then
+  echo "Error: $DIR already exists"
+  exit 1
+fi
+
+mkdir "$DIR"
+
+
+
+
 curl -fsSL "https://projecteuler.net/minimal=${PROB}" \
 | pandoc -f html -t gfm \
 > "$DIR/p${PROB}.md"
 
-# -----------------------
-# Language-specific files
-# -----------------------
+
+
+
 case "$LANG" in
   c)
     cat > "$DIR/main.c" << 'EOF'
@@ -68,13 +73,18 @@ EOF
     cat > "$DIR/main.jl" << 'EOF'
 using Printf
 
-t0 = time()
+function main()
+    t0 = time_ns()
 
 
 
-t1 = time()
+    t1 = time_ns()
 
-@printf("Time: %f seconds\n", t1 - t0)
+    cpu_time_used = (t1 - t0) / 1e9
+    @printf("Time: %f seconds\n", cpu_time_used)
+end
+
+main()
 EOF
     ;;
   *)
